name: Python CI

on: [push, pull_request] # Triggers the workflow on push or pull request events

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Specifies the runner environment
    strategy:
      matrix: # Test on multiple Python versions
        python-version: ["3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checks out your repository

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirments.txt

      - name: Lint with Ruff
        run: |
          ruff check .  # Check for linting errors
          ruff format --check . # Check for formatting issues

      - name: Test with Pytest
        run: |
          pytest test/ # Or simply `pytest`

      - name: Run main script (optional smoke test)
        if: matrix.python-version == '3.11' # Only run for one version to save time
        run: |
          echo -e "5\n3\n+" | python main.py # Provide sample input